//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RaceLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Generated {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRaceLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class RaceLangBaseListener : IRaceLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.name_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName_token([NotNull] RaceLangParser.Name_tokenContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.name_token"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName_token([NotNull] RaceLangParser.Name_tokenContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] RaceLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] RaceLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] RaceLangParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] RaceLangParser.ModuleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.import_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_stmt([NotNull] RaceLangParser.Import_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.import_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_stmt([NotNull] RaceLangParser.Import_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.top_level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level([NotNull] RaceLangParser.Top_levelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.top_level"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level([NotNull] RaceLangParser.Top_levelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.top_level_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTop_level_item([NotNull] RaceLangParser.Top_level_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.top_level_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTop_level_item([NotNull] RaceLangParser.Top_level_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.struct_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_decl([NotNull] RaceLangParser.Struct_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.struct_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_decl([NotNull] RaceLangParser.Struct_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.field_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_decl([NotNull] RaceLangParser.Field_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.field_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_decl([NotNull] RaceLangParser.Field_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] RaceLangParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] RaceLangParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.system_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSystem_decl([NotNull] RaceLangParser.System_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.system_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSystem_decl([NotNull] RaceLangParser.System_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.param_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam_list([NotNull] RaceLangParser.Param_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.param_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam_list([NotNull] RaceLangParser.Param_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] RaceLangParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] RaceLangParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.component_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponent_list([NotNull] RaceLangParser.Component_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.component_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponent_list([NotNull] RaceLangParser.Component_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.car_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCar_instance([NotNull] RaceLangParser.Car_instanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.car_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCar_instance([NotNull] RaceLangParser.Car_instanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.engine_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEngine_instance([NotNull] RaceLangParser.Engine_instanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.engine_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEngine_instance([NotNull] RaceLangParser.Engine_instanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.track_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrack_instance([NotNull] RaceLangParser.Track_instanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.track_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrack_instance([NotNull] RaceLangParser.Track_instanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.race_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRace_instance([NotNull] RaceLangParser.Race_instanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.race_instance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRace_instance([NotNull] RaceLangParser.Race_instanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.field_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_value([NotNull] RaceLangParser.Field_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.field_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_value([NotNull] RaceLangParser.Field_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.function_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_decl([NotNull] RaceLangParser.Function_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.function_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_decl([NotNull] RaceLangParser.Function_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] RaceLangParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] RaceLangParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] RaceLangParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] RaceLangParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.var_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl_stmt([NotNull] RaceLangParser.Var_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.var_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl_stmt([NotNull] RaceLangParser.Var_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLvalue([NotNull] RaceLangParser.LvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.lvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLvalue([NotNull] RaceLangParser.LvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] RaceLangParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] RaceLangParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stmt([NotNull] RaceLangParser.If_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stmt([NotNull] RaceLangParser.If_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_stmt([NotNull] RaceLangParser.For_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_stmt([NotNull] RaceLangParser.For_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.expression_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_stmt([NotNull] RaceLangParser.Expression_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.expression_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_stmt([NotNull] RaceLangParser.Expression_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_stmt([NotNull] RaceLangParser.Return_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_stmt([NotNull] RaceLangParser.Return_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] RaceLangParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] RaceLangParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDivExpr([NotNull] RaceLangParser.MulDivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDivExpr([NotNull] RaceLangParser.MulDivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PassUp1</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPassUp1([NotNull] RaceLangParser.PassUp1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PassUp1</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPassUp1([NotNull] RaceLangParser.PassUp1Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PassUp2</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPassUp2([NotNull] RaceLangParser.PassUp2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PassUp2</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPassUp2([NotNull] RaceLangParser.PassUp2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSubExpr([NotNull] RaceLangParser.AddSubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSubExpr([NotNull] RaceLangParser.AddSubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PassUp3</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPassUp3([NotNull] RaceLangParser.PassUp3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PassUp3</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPassUp3([NotNull] RaceLangParser.PassUp3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CompareExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareExpr([NotNull] RaceLangParser.CompareExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CompareExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareExpr([NotNull] RaceLangParser.CompareExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinusExpr([NotNull] RaceLangParser.UnaryMinusExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinusExpr([NotNull] RaceLangParser.UnaryMinusExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryNotExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryNotExpr([NotNull] RaceLangParser.UnaryNotExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryNotExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryNotExpr([NotNull] RaceLangParser.UnaryNotExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.postfix_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_expr([NotNull] RaceLangParser.Postfix_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.postfix_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_expr([NotNull] RaceLangParser.Postfix_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.postfix_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_op([NotNull] RaceLangParser.Postfix_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.postfix_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_op([NotNull] RaceLangParser.Postfix_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArg_list([NotNull] RaceLangParser.Arg_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.arg_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArg_list([NotNull] RaceLangParser.Arg_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpr([NotNull] RaceLangParser.LiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpr([NotNull] RaceLangParser.LiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdExpr([NotNull] RaceLangParser.IdExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdExpr([NotNull] RaceLangParser.IdExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayExpr([NotNull] RaceLangParser.ArrayExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayExpr([NotNull] RaceLangParser.ArrayExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>StructInit</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructInit([NotNull] RaceLangParser.StructInitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>StructInit</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructInit([NotNull] RaceLangParser.StructInitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExpr([NotNull] RaceLangParser.ParenExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExpr([NotNull] RaceLangParser.ParenExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] RaceLangParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] RaceLangParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.array_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_expr([NotNull] RaceLangParser.Array_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.array_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_expr([NotNull] RaceLangParser.Array_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.struct_init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_init([NotNull] RaceLangParser.Struct_initContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.struct_init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_init([NotNull] RaceLangParser.Struct_initContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.init_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit_field([NotNull] RaceLangParser.Init_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.init_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit_field([NotNull] RaceLangParser.Init_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.shader_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShader_decl([NotNull] RaceLangParser.Shader_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.shader_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShader_decl([NotNull] RaceLangParser.Shader_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.shader_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShader_type([NotNull] RaceLangParser.Shader_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.shader_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShader_type([NotNull] RaceLangParser.Shader_typeContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Generated
