//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RaceLang.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Generated {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RaceLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IRaceLangListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.name_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName_token([NotNull] RaceLangParser.Name_tokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.name_token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName_token([NotNull] RaceLangParser.Name_tokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] RaceLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] RaceLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] RaceLangParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] RaceLangParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImport_stmt([NotNull] RaceLangParser.Import_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.import_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImport_stmt([NotNull] RaceLangParser.Import_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.top_level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level([NotNull] RaceLangParser.Top_levelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.top_level"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level([NotNull] RaceLangParser.Top_levelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.top_level_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTop_level_item([NotNull] RaceLangParser.Top_level_itemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.top_level_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTop_level_item([NotNull] RaceLangParser.Top_level_itemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.struct_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_decl([NotNull] RaceLangParser.Struct_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.struct_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_decl([NotNull] RaceLangParser.Struct_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.field_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_decl([NotNull] RaceLangParser.Field_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.field_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_decl([NotNull] RaceLangParser.Field_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] RaceLangParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] RaceLangParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.system_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSystem_decl([NotNull] RaceLangParser.System_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.system_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSystem_decl([NotNull] RaceLangParser.System_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_list([NotNull] RaceLangParser.Param_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.param_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_list([NotNull] RaceLangParser.Param_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] RaceLangParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] RaceLangParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.component_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponent_list([NotNull] RaceLangParser.Component_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.component_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponent_list([NotNull] RaceLangParser.Component_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.car_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCar_instance([NotNull] RaceLangParser.Car_instanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.car_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCar_instance([NotNull] RaceLangParser.Car_instanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.engine_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEngine_instance([NotNull] RaceLangParser.Engine_instanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.engine_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEngine_instance([NotNull] RaceLangParser.Engine_instanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.track_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrack_instance([NotNull] RaceLangParser.Track_instanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.track_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrack_instance([NotNull] RaceLangParser.Track_instanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.race_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRace_instance([NotNull] RaceLangParser.Race_instanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.race_instance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRace_instance([NotNull] RaceLangParser.Race_instanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.field_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_value([NotNull] RaceLangParser.Field_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.field_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_value([NotNull] RaceLangParser.Field_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.function_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_decl([NotNull] RaceLangParser.Function_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.function_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_decl([NotNull] RaceLangParser.Function_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] RaceLangParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] RaceLangParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] RaceLangParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] RaceLangParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.var_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl_stmt([NotNull] RaceLangParser.Var_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.var_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl_stmt([NotNull] RaceLangParser.Var_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLvalue([NotNull] RaceLangParser.LvalueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.lvalue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLvalue([NotNull] RaceLangParser.LvalueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] RaceLangParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] RaceLangParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] RaceLangParser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] RaceLangParser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_stmt([NotNull] RaceLangParser.For_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_stmt([NotNull] RaceLangParser.For_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.expression_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_stmt([NotNull] RaceLangParser.Expression_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.expression_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_stmt([NotNull] RaceLangParser.Expression_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stmt([NotNull] RaceLangParser.Return_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stmt([NotNull] RaceLangParser.Return_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] RaceLangParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] RaceLangParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDivExpr([NotNull] RaceLangParser.MulDivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDivExpr([NotNull] RaceLangParser.MulDivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PassUp1</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPassUp1([NotNull] RaceLangParser.PassUp1Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PassUp1</c>
	/// labeled alternative in <see cref="RaceLangParser.expr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPassUp1([NotNull] RaceLangParser.PassUp1Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PassUp2</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPassUp2([NotNull] RaceLangParser.PassUp2Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PassUp2</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPassUp2([NotNull] RaceLangParser.PassUp2Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSubExpr([NotNull] RaceLangParser.AddSubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSubExpr([NotNull] RaceLangParser.AddSubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PassUp3</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPassUp3([NotNull] RaceLangParser.PassUp3Context context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PassUp3</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPassUp3([NotNull] RaceLangParser.PassUp3Context context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CompareExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareExpr([NotNull] RaceLangParser.CompareExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CompareExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareExpr([NotNull] RaceLangParser.CompareExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinusExpr([NotNull] RaceLangParser.UnaryMinusExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinusExpr([NotNull] RaceLangParser.UnaryMinusExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryNotExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryNotExpr([NotNull] RaceLangParser.UnaryNotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryNotExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.expr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryNotExpr([NotNull] RaceLangParser.UnaryNotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.postfix_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_expr([NotNull] RaceLangParser.Postfix_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.postfix_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_expr([NotNull] RaceLangParser.Postfix_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.postfix_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_op([NotNull] RaceLangParser.Postfix_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.postfix_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_op([NotNull] RaceLangParser.Postfix_opContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg_list([NotNull] RaceLangParser.Arg_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.arg_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg_list([NotNull] RaceLangParser.Arg_listContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpr([NotNull] RaceLangParser.LiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LiteralExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpr([NotNull] RaceLangParser.LiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdExpr([NotNull] RaceLangParser.IdExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdExpr([NotNull] RaceLangParser.IdExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayExpr([NotNull] RaceLangParser.ArrayExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayExpr([NotNull] RaceLangParser.ArrayExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>StructInit</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructInit([NotNull] RaceLangParser.StructInitContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>StructInit</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructInit([NotNull] RaceLangParser.StructInitContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] RaceLangParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="RaceLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] RaceLangParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] RaceLangParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] RaceLangParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.array_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_expr([NotNull] RaceLangParser.Array_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.array_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_expr([NotNull] RaceLangParser.Array_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.struct_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_init([NotNull] RaceLangParser.Struct_initContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.struct_init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_init([NotNull] RaceLangParser.Struct_initContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.init_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit_field([NotNull] RaceLangParser.Init_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.init_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit_field([NotNull] RaceLangParser.Init_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.shader_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShader_decl([NotNull] RaceLangParser.Shader_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.shader_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShader_decl([NotNull] RaceLangParser.Shader_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RaceLangParser.shader_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShader_type([NotNull] RaceLangParser.Shader_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RaceLangParser.shader_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShader_type([NotNull] RaceLangParser.Shader_typeContext context);
}
} // namespace Generated
